### ISSUE TITLE
not ready yet?

### ISSUE THREAD

**Issue by mmmgigi** [SchumacherFM/Magento-FastIndexer#1]
Hi,

I get:
PHP message: PHP Fatal error:  Class name must be a valid object or a string in /www/fashionsport.ro_test/app/code/core/Mage/Core/Model/Resource.php on line 215
when I enable 
<type><![CDATA[pdo_mysql_fastindexer]]></type>
in local.xml

**Comment by mmmgigi** [comment]
Sorry, my mistake.
I forgot to add the new resource.

**Comment by SchumacherFM** [comment]
👍
